name: Deploy to CoreServer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Deploy to subdomain
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public_html/
        server-dir: /public_html/m-nishida.geo.jp/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/database/
          
    - name: Deploy database files to subdomain
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./database/
        server-dir: /public_html/m-nishida.geo.jp/database/